#!/usr/bin/env python3
"""Build and validate distributable plugin packages for vgc-coach."""

from __future__ import annotations

import argparse
import ast
import filecmp
import json
import shutil
import sys
import tempfile
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Dict, Iterable, List


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "tools" / "plugin_manifest.json"
VERSION_PATH = ROOT / "VERSION"
RELEASE_NOTES_PATH = ROOT / "RELEASE_NOTES.md"
GENERATED_COMMENT = "<!-- Generated by tools/build_plugins.py -->"


@dataclass(frozen=True)
class SkillInfo:
    name: str
    display_name: str
    short_description: str
    default_prompt: str


def load_manifest() -> dict:
    return json.loads(MANIFEST_PATH.read_text())


def load_version() -> str:
    return VERSION_PATH.read_text().strip()


def parse_openai_metadata(path: Path) -> SkillInfo:
    values: Dict[str, str] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.rstrip()
        if not line.startswith("  ") or ":" not in line:
            continue
        key, raw_value = line.strip().split(":", 1)
        raw_value = raw_value.strip()
        if not raw_value:
            continue
        values[key] = ast.literal_eval(raw_value)
    return SkillInfo(
        name=path.parent.parent.name,
        display_name=values["display_name"],
        short_description=values["short_description"],
        default_prompt=values["default_prompt"],
    )


def load_skills(manifest: dict) -> Dict[str, SkillInfo]:
    skills: Dict[str, SkillInfo] = {}
    for entry in manifest["skills"]:
        metadata_path = ROOT / entry["codex_metadata"]
        info = parse_openai_metadata(metadata_path)
        skills[entry["name"]] = info
    return skills


def trim_codex_prompt(prompt: str) -> str:
    prompt = prompt.strip()
    if len(prompt) <= 128:
        return prompt
    return prompt[:125].rstrip() + "..."


def ensure_parent(path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)


def write_text(path: Path, content: str) -> None:
    ensure_parent(path)
    path.write_text(content)


def write_json(path: Path, payload: dict) -> None:
    ensure_parent(path)
    path.write_text(json.dumps(payload, indent=2) + "\n")


def copy_path(src: Path, dest: Path) -> None:
    if src.is_dir():
        shutil.copytree(src, dest, dirs_exist_ok=True)
        return
    ensure_parent(dest)
    shutil.copy2(src, dest)


def unique_paths(paths: Iterable[str]) -> List[str]:
    seen = set()
    ordered: List[str] = []
    for path in paths:
        if path not in seen:
            ordered.append(path)
            seen.add(path)
    return ordered


def collect_skill_docs(manifest: dict) -> List[str]:
    docs: List[str] = []
    for entry in manifest["skills"]:
        docs.extend(entry["docs"])
    return unique_paths(docs)


def ignore_hidden_entries(_directory: str, entries: List[str]) -> List[str]:
    return [entry for entry in entries if entry.startswith(".")]


def runtime_doc_basename(runtime: str) -> str:
    return {
        "codex": "codex.md",
        "claude": "claude-code.md",
        "opencode": "opencode.md",
    }[runtime]


def render_plugin_readme(plugin: dict, manifest: dict, skills: Dict[str, SkillInfo], version: str) -> str:
    runtime_name = {
        "codex": "Codex",
        "claude": "Claude Code",
        "opencode": "OpenCode",
    }[plugin["runtime"]]
    skill_lines = "\n".join(
        f"- `{skill.name}`: {skill.short_description}" for skill in skills.values()
    )
    return f"""# VGC Coach for {runtime_name}

{GENERATED_COMMENT}

Version: `{version}`

This package is generated from the canonical shared skill source in `vgc-coach`.
It is intentionally self-contained: the skills, supporting docs, eval artifacts, and exact-calc helper live inside this plugin package so installs do not depend on repo-local symlinks.

## Included Skills

{skill_lines}

## Runtime Docs

- `docs/runtime/{runtime_doc_basename(plugin["runtime"])}`

## Packaging Rules

- Shared coaching logic comes from `skills/`
- Supporting references and examples come from `docs/skills/`
- The exact damage helper lives at `tools/browser_damage_calc.py`
- Generated files should be refreshed with `python3 tools/build_plugins.py`
"""


def render_package_runtime_doc(plugin: dict) -> str:
    runtime_name = {
        "codex": "Codex",
        "claude": "Claude Code",
        "opencode": "OpenCode",
    }[plugin["runtime"]]
    return f"""# {runtime_name} Runtime

{GENERATED_COMMENT}

This plugin package is a generated, self-contained distribution of VGC Coach.

## Package Contents

- `skills/` contains the shared coaching skills
- `docs/skills/` contains supporting references and examples
- `data/fixtures/evals/` and `data/rubrics/` contain evaluation artifacts
- `tools/browser_damage_calc.py` provides the optional exact damage helper

## Notes

- This package is generated from the canonical repo source. Do not edit the packaged copies by hand.
- Runtime-specific install and update instructions are maintained in the main repository docs for `vgc-coach`.
"""


def render_codex_manifest(plugin: dict, repo_meta: dict, skills: Dict[str, SkillInfo], version: str) -> dict:
    prompts = [
        trim_codex_prompt(skills[name].default_prompt)
        for name in plugin["default_prompt_skills"]
    ]
    return {
        "name": plugin["name"],
        "version": version,
        "description": plugin["description"],
        "author": repo_meta["author"],
        "homepage": repo_meta["homepage"],
        "repository": repo_meta["repository"],
        "license": repo_meta["license"],
        "keywords": plugin["keywords"],
        "skills": "./skills/",
        "interface": {
            "displayName": "VGC Coach",
            "shortDescription": "Pokemon Champions coaching skills for Codex",
            "longDescription": "Installable Pokemon Champions coaching workflows generated from the canonical shared VGC Coach skill packages.",
            "developerName": repo_meta["author"]["name"],
            "category": "Productivity",
            "capabilities": plugin["capabilities"],
            "websiteURL": repo_meta["homepage"],
            "defaultPrompt": prompts,
            "brandColor": plugin["brand_color"],
        },
    }


def render_claude_manifest(plugin: dict, repo_meta: dict, version: str) -> dict:
    return {
        "name": plugin["name"],
        "description": plugin["description"],
        "version": version,
        "author": repo_meta["author"],
        "homepage": repo_meta["homepage"],
        "repository": repo_meta["repository"],
        "license": repo_meta["license"],
        "keywords": plugin["keywords"],
    }


def render_opencode_package_json(plugin: dict, repo_meta: dict, version: str) -> dict:
    return {
        "name": plugin["name"],
        "version": version,
        "type": "module",
        "description": plugin["description"],
        "homepage": repo_meta["homepage"],
        "repository": repo_meta["repository"],
        "license": repo_meta["license"],
        "keywords": plugin["keywords"],
        "main": "./.opencode/plugins/vgc-coach.js",
    }


def render_opencode_plugin_js(plugin_name: str) -> str:
    return f"""import path from 'path';
import {{ fileURLToPath }} from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const VgcCoachPlugin = async () => {{
  const pluginRoot = path.resolve(__dirname, '..', '..');
  const skillsDir = path.join(pluginRoot, 'skills');

  return {{
    config: async (config) => {{
      config.skills = config.skills || {{}};
      config.skills.paths = config.skills.paths || [];
      if (!config.skills.paths.includes(skillsDir)) {{
        config.skills.paths.push(skillsDir);
      }}
    }},
  }};
}};
"""


def render_root_package_json(plugin: dict, repo_meta: dict, version: str) -> dict:
    return {
        "name": plugin["name"],
        "version": version,
        "type": "module",
        "description": plugin["description"],
        "homepage": repo_meta["homepage"],
        "repository": repo_meta["repository"],
        "license": repo_meta["license"],
        "keywords": plugin["keywords"],
        "main": "./plugins/vgc-coach-opencode/.opencode/plugins/vgc-coach.js",
    }


def render_codex_marketplace(version: str) -> dict:
    return {
        "name": "vgc-coach",
        "interface": {
            "displayName": "VGC Coach",
        },
        "plugins": [
            {
                "name": "vgc-coach-codex",
                "source": {
                    "source": "local",
                    "path": "./plugins/vgc-coach-codex",
                },
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": "Productivity",
            }
        ],
    }


def render_claude_marketplace(repo_meta: dict, version: str) -> dict:
    return {
        "name": "vgc-coach",
        "owner": repo_meta["author"],
        "metadata": {
            "description": "Pokemon Champions coaching plugins generated from the shared VGC Coach skill packages.",
            "version": version,
            "pluginRoot": "./plugins",
        },
        "plugins": [
            {
                "name": "vgc-coach-claude",
                "source": "./plugins/vgc-coach-claude",
                "description": "Pokemon Champions coaching skills for Claude Code.",
                "version": version,
                "author": repo_meta["author"],
            }
        ],
    }


def render_release_notes(manifest: dict, version: str) -> str:
    today = date.today().isoformat()
    bullets = "\n".join(f"- {item}" for item in manifest["release_notes"]["summary"])
    return f"""# Release Notes

{GENERATED_COMMENT}

## {version} - {today}

{bullets}
"""


def build_plugin(plugin: dict, manifest: dict, skills: Dict[str, SkillInfo], version: str, target_root: Path) -> None:
    repo_meta = manifest["repository"]
    destination = target_root / "plugins" / plugin["name"]
    if destination.exists():
        shutil.rmtree(destination)
    destination.mkdir(parents=True, exist_ok=True)

    for relative in manifest["shared_copy"]["files"]:
        copy_path(ROOT / relative, destination / relative)
    for relative in manifest["shared_copy"]["directories"]:
        copy_path(ROOT / relative, destination / relative)
    for relative in manifest["shared_copy"]["tools"]:
        copy_path(ROOT / relative, destination / relative)

    for skill_name in skills:
        shutil.copytree(
            ROOT / "skills" / skill_name,
            destination / "skills" / skill_name,
            ignore=ignore_hidden_entries,
        )

    for relative in collect_skill_docs(manifest):
        copy_path(ROOT / relative, destination / relative)

    for relative in plugin["runtime_docs"]:
        if relative.endswith(".md") and "docs/runtime/" in relative:
            write_text(destination / relative, render_package_runtime_doc(plugin))
            continue
        copy_path(ROOT / relative, destination / relative)

    write_text(destination / "README.md", render_plugin_readme(plugin, manifest, skills, version))

    if plugin["runtime"] == "codex":
        write_json(
            destination / plugin["manifest_path"],
            render_codex_manifest(plugin, repo_meta, skills, version),
        )
        return

    if plugin["runtime"] == "claude":
        write_json(
            destination / plugin["manifest_path"],
            render_claude_manifest(plugin, repo_meta, version),
        )
        return

    if plugin["runtime"] == "opencode":
        write_json(
            destination / plugin["manifest_path"],
            render_opencode_package_json(plugin, repo_meta, version),
        )
        write_text(
            destination / ".opencode" / "plugins" / "vgc-coach.js",
            render_opencode_plugin_js(plugin["name"]),
        )
        return

    raise ValueError(f"Unsupported runtime: {plugin['runtime']}")


def build_root_outputs(manifest: dict, version: str, target_root: Path) -> None:
    repo_meta = manifest["repository"]
    opencode_plugin = next(
        plugin for plugin in manifest["plugins"] if plugin["runtime"] == "opencode"
    )
    write_json(
        target_root / ".agents" / "plugins" / "marketplace.json",
        render_codex_marketplace(version),
    )
    write_json(
        target_root / ".claude-plugin" / "marketplace.json",
        render_claude_marketplace(repo_meta, version),
    )
    write_json(
        target_root / "package.json",
        render_root_package_json(opencode_plugin, repo_meta, version),
    )


def build_all(target_root: Path) -> None:
    manifest = load_manifest()
    version = load_version()
    skills = load_skills(manifest)
    for plugin in manifest["plugins"]:
        build_plugin(plugin, manifest, skills, version, target_root)
    build_root_outputs(manifest, version, target_root)


def compare_directories(expected: Path, actual: Path) -> List[str]:
    differences: List[str] = []
    comparison = filecmp.dircmp(expected, actual)
    for name in comparison.left_only:
        differences.append(f"Missing in repo: {actual / name}")
    for name in comparison.right_only:
        differences.append(f"Unexpected in repo: {actual / name}")
    for name in comparison.diff_files:
        differences.append(f"Changed file: {actual / name}")
    for subdir in comparison.common_dirs:
        differences.extend(compare_directories(expected / subdir, actual / subdir))
    return differences


def validate_no_symlinks(root: Path) -> List[str]:
    issues: List[str] = []
    for path in root.rglob("*"):
        if path.is_symlink():
            issues.append(f"Symlink not allowed: {path}")
    return issues


def validate_no_workspace_references(root: Path) -> List[str]:
    issues: List[str] = []
    forbidden = [
        ".agents/skills/",
        ".claude/skills/",
        ".opencode/skills/",
        str(ROOT),
    ]
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        try:
            content = path.read_text()
        except UnicodeDecodeError:
            continue
        for needle in forbidden:
            if needle in content:
                issues.append(f"Workspace-only reference in {path}: {needle}")
    return issues


def validate_generated_outputs(target_root: Path) -> List[str]:
    issues: List[str] = []
    plugins_dir = target_root / "plugins"
    if plugins_dir.exists():
        issues.extend(validate_no_symlinks(plugins_dir))
        issues.extend(validate_no_workspace_references(plugins_dir))
    return issues


def check_repo() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        temp_root = Path(tmp)
        build_all(temp_root)
        differences: List[str] = []
        differences.extend(compare_directories(temp_root / "plugins", ROOT / "plugins"))
        for relative in [
            ".agents/plugins/marketplace.json",
            ".claude-plugin/marketplace.json",
            "package.json",
        ]:
            if not (ROOT / relative).exists():
                differences.append(f"Missing generated file: {ROOT / relative}")
                continue
            if (temp_root / relative).read_text() != (ROOT / relative).read_text():
                differences.append(f"Changed file: {ROOT / relative}")
        expected_release_notes = render_release_notes(load_manifest(), load_version())
        if not RELEASE_NOTES_PATH.exists():
            differences.append(f"Missing generated file: {RELEASE_NOTES_PATH}")
        elif RELEASE_NOTES_PATH.read_text() != expected_release_notes:
            differences.append(f"Changed file: {RELEASE_NOTES_PATH}")
        differences.extend(validate_generated_outputs(ROOT))
        if differences:
            for issue in differences:
                print(issue, file=sys.stderr)
            return 1
    return 0


def update_release_notes() -> None:
    manifest = load_manifest()
    version = load_version()
    RELEASE_NOTES_PATH.write_text(render_release_notes(manifest, version))


def print_release_notes() -> None:
    manifest = load_manifest()
    version = load_version()
    print(render_release_notes(manifest, version))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("build")
    subparsers.add_parser("check")
    subparsers.add_parser("update-release-notes")
    subparsers.add_parser("print-release-notes")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.command == "build":
        build_all(ROOT)
        return 0
    if args.command == "check":
        return check_repo()
    if args.command == "update-release-notes":
        update_release_notes()
        return 0
    if args.command == "print-release-notes":
        print_release_notes()
        return 0
    raise ValueError(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
