#!/usr/bin/env python3
"""Build and validate distributable plugin packages for vgc-coach."""

from __future__ import annotations

import argparse
import ast
import filecmp
import json
import os
import shutil
import stat
import sys
import tempfile
import unicodedata
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Callable, Dict, Iterable, List


ROOT = Path(__file__).resolve().parents[1]
MANIFEST_PATH = ROOT / "tools" / "plugin_manifest.json"
VERSION_PATH = ROOT / "VERSION"
RELEASE_NOTES_PATH = ROOT / "RELEASE_NOTES.md"
GENERATED_COMMENT = "<!-- Generated by tools/build_plugins.py -->"


@dataclass(frozen=True)
class SkillInfo:
    name: str
    display_name: str
    short_description: str
    default_prompt: str


def load_manifest() -> dict:
    _prewalk_source_tree(MANIFEST_PATH)
    return json.loads(MANIFEST_PATH.read_text())


def load_version() -> str:
    _prewalk_source_tree(VERSION_PATH)
    return VERSION_PATH.read_text().strip()


def validate_relative_posix_path(value: object, field: str) -> str:
    if not isinstance(value, str):
        raise ValueError(f"{field} must be a normalized repository-relative POSIX path")
    components = value.split("/")
    invalid = (
        not value
        or value.startswith("/")
        or "\\" in value
        or any(unicodedata.category(character) == "Cc" for character in value)
        or any(component in {"", ".", ".."} for component in components)
        or PurePosixPath(value).is_absolute()
        or PurePosixPath(value).as_posix() != value
    )
    if invalid:
        raise ValueError(
            f"{field} must be a normalized repository-relative POSIX path: {value!r}"
        )
    return value


def validate_manifest_paths(manifest: dict) -> None:
    for index, entry in enumerate(manifest["skills"]):
        validate_relative_posix_path(entry["name"], f"skills[{index}].name")
        validate_relative_posix_path(
            entry["codex_metadata"], f"skills[{index}].codex_metadata"
        )
        for doc_index, relative in enumerate(entry["docs"]):
            validate_relative_posix_path(
                relative, f"skills[{index}].docs[{doc_index}]"
            )

    for collection in ("files", "directories", "tools"):
        for index, relative in enumerate(manifest["shared_copy"][collection]):
            validate_relative_posix_path(
                relative, f"shared_copy.{collection}[{index}]"
            )

    for index, plugin in enumerate(manifest["plugins"]):
        validate_relative_posix_path(plugin["name"], f"plugins[{index}].name")
        validate_relative_posix_path(
            plugin["manifest_path"], f"plugins[{index}].manifest_path"
        )
        for doc_index, relative in enumerate(plugin["runtime_docs"]):
            validate_relative_posix_path(
                relative, f"plugins[{index}].runtime_docs[{doc_index}]"
            )


def assert_destination_contained(intended_root: Path, destination: Path) -> None:
    logical_root = Path(os.path.abspath(intended_root))
    logical_destination = Path(os.path.abspath(destination))
    try:
        relative = logical_destination.relative_to(logical_root)
    except ValueError as exc:
        raise ValueError(
            f"Destination outside intended root {logical_root}: {destination}"
        ) from exc

    resolved_root = intended_root.resolve(strict=False)
    resolved_destination = destination.resolve(strict=False)
    try:
        resolved_destination.relative_to(resolved_root)
    except ValueError as exc:
        raise ValueError(
            f"Destination outside intended root {resolved_root}: {destination}"
        ) from exc

    current = logical_root
    for component in (None, *relative.parts):
        if component is not None:
            current = current / component
        if current.is_symlink():
            raise ValueError(f"Destination symlink not allowed: {current}")


def safe_mkdir(path: Path, intended_root: Path) -> None:
    assert_destination_contained(intended_root, path)
    path.mkdir(parents=True, exist_ok=True)


def safe_rmtree(path: Path, intended_root: Path) -> None:
    assert_destination_contained(intended_root, path)
    shutil.rmtree(path)


def _assert_source_components_not_symlinks(path: Path) -> None:
    try:
        relative = path.relative_to(ROOT)
    except ValueError as exc:
        raise ValueError(f"Source outside repository root: {path}") from exc
    current = ROOT
    for component in relative.parts:
        current = current / component
        mode = current.lstat().st_mode
        if stat.S_ISLNK(mode):
            raise ValueError(f"Source symlink not allowed: {current}")


def _prewalk_source_tree(path: Path) -> None:
    _assert_source_components_not_symlinks(path)
    mode = path.lstat().st_mode
    if stat.S_ISLNK(mode):
        raise ValueError(f"Source symlink not allowed: {path}")
    if not stat.S_ISDIR(mode):
        return
    with os.scandir(path) as entries:
        for entry in entries:
            entry_path = Path(entry.path)
            entry_mode = entry.stat(follow_symlinks=False).st_mode
            if stat.S_ISLNK(entry_mode):
                raise ValueError(f"Source symlink not allowed: {entry_path}")
            if stat.S_ISDIR(entry_mode):
                _prewalk_source_tree(entry_path)


def canonical_source_paths(manifest: dict) -> List[Path]:
    relative_paths: List[str] = []
    for collection in ("files", "directories", "tools"):
        relative_paths.extend(manifest["shared_copy"][collection])
    for entry in manifest["skills"]:
        relative_paths.append(entry["codex_metadata"])
        relative_paths.append(f"skills/{entry['name']}")
        relative_paths.extend(entry["docs"])
    for plugin in manifest["plugins"]:
        relative_paths.extend(plugin["runtime_docs"])
    return [ROOT / relative for relative in unique_paths(relative_paths)]


def validate_canonical_sources(manifest: dict) -> None:
    for source in canonical_source_paths(manifest):
        _prewalk_source_tree(source)


def parse_openai_metadata(path: Path) -> SkillInfo:
    values: Dict[str, str] = {}
    for raw_line in path.read_text().splitlines():
        line = raw_line.rstrip()
        if not line.startswith("  ") or ":" not in line:
            continue
        key, raw_value = line.strip().split(":", 1)
        raw_value = raw_value.strip()
        if not raw_value:
            continue
        values[key] = ast.literal_eval(raw_value)
    return SkillInfo(
        name=path.parent.parent.name,
        display_name=values["display_name"],
        short_description=values["short_description"],
        default_prompt=values["default_prompt"],
    )


def load_skills(manifest: dict) -> Dict[str, SkillInfo]:
    skills: Dict[str, SkillInfo] = {}
    for entry in manifest["skills"]:
        metadata_path = ROOT / entry["codex_metadata"]
        info = parse_openai_metadata(metadata_path)
        skills[entry["name"]] = info
    return skills


def trim_codex_prompt(prompt: str) -> str:
    prompt = prompt.strip()
    if len(prompt) <= 128:
        return prompt
    return prompt[:125].rstrip() + "..."


def ensure_parent(path: Path, intended_root: Path) -> None:
    safe_mkdir(path.parent, intended_root)


def write_text(path: Path, content: str, intended_root: Path) -> None:
    assert_destination_contained(intended_root, path)
    ensure_parent(path, intended_root)
    assert_destination_contained(intended_root, path)
    path.write_text(content)


def write_json(path: Path, payload: dict, intended_root: Path) -> None:
    assert_destination_contained(intended_root, path)
    ensure_parent(path, intended_root)
    assert_destination_contained(intended_root, path)
    path.write_text(json.dumps(payload, indent=2) + "\n")


def copy_path(
    src: Path,
    dest: Path,
    intended_root: Path,
    *,
    ignore: Callable[[str, List[str]], List[str]] | None = None,
) -> None:
    source_mode = src.lstat().st_mode
    if stat.S_ISLNK(source_mode):
        raise ValueError(f"Source symlink not allowed: {src}")
    if stat.S_ISDIR(source_mode):
        assert_destination_contained(intended_root, dest)
        safe_mkdir(dest, intended_root)
        with os.scandir(src) as entries:
            ordered_entries = sorted(entries, key=lambda entry: entry.name)
        ignored = (
            set(ignore(str(src), [entry.name for entry in ordered_entries]))
            if ignore
            else set()
        )
        for entry in ordered_entries:
            if entry.name in ignored:
                continue
            copy_path(
                Path(entry.path),
                dest / entry.name,
                intended_root,
                ignore=ignore,
            )
        return
    assert_destination_contained(intended_root, dest)
    ensure_parent(dest, intended_root)
    assert_destination_contained(intended_root, dest)
    shutil.copy2(src, dest, follow_symlinks=False)


def unique_paths(paths: Iterable[str]) -> List[str]:
    seen = set()
    ordered: List[str] = []
    for path in paths:
        if path not in seen:
            ordered.append(path)
            seen.add(path)
    return ordered


def collect_skill_docs(manifest: dict) -> List[str]:
    docs: List[str] = []
    for entry in manifest["skills"]:
        docs.extend(entry["docs"])
    return unique_paths(docs)


def ignore_hidden_entries(_directory: str, entries: List[str]) -> List[str]:
    return [entry for entry in entries if entry.startswith(".")]


def runtime_doc_basename(runtime: str) -> str:
    return {
        "codex": "codex.md",
        "claude": "claude-code.md",
        "opencode": "opencode.md",
    }[runtime]


def render_plugin_readme(plugin: dict, manifest: dict, skills: Dict[str, SkillInfo], version: str) -> str:
    runtime_name = {
        "codex": "Codex",
        "claude": "Claude Code",
        "opencode": "OpenCode",
    }[plugin["runtime"]]
    skill_lines = "\n".join(
        f"- `{skill.name}`: {skill.short_description}" for skill in skills.values()
    )
    return f"""# VGC Coach for {runtime_name}

{GENERATED_COMMENT}

Version: `{version}`

This package is generated from the canonical shared skill source in `vgc-coach`.
It is intentionally self-contained: the skills, supporting docs, eval artifacts,
battle-state contract, local ingestion helper, and exact-calc helper live inside
this plugin package so installs do not depend on repo-local symlinks.

## Included Skills

{skill_lines}

## Runtime Docs

- `docs/runtime/{runtime_doc_basename(plugin["runtime"])}`

## Packaging Rules

- Shared coaching logic comes from `skills/`
- Supporting references and examples come from `docs/skills/`
- The runtime-neutral battle contract lives at `data/schemas/battle-state-v1.schema.json`
- The bounded local normalizer lives at `tools/ingest_battle_state.py`
- The exact damage helper lives at `tools/browser_damage_calc.py`
- Generated files should be refreshed with `python3 tools/build_plugins.py`
"""


def render_package_runtime_doc(plugin: dict) -> str:
    runtime_name = {
        "codex": "Codex",
        "claude": "Claude Code",
        "opencode": "OpenCode",
    }[plugin["runtime"]]
    return f"""# {runtime_name} Runtime

{GENERATED_COMMENT}

This plugin package is a generated, self-contained distribution of VGC Coach.

## Package Contents

- `skills/` contains the shared coaching skills
- `docs/skills/` contains supporting references and examples
- `data/fixtures/evals/` and `data/rubrics/` contain evaluation artifacts
- `data/schemas/battle-state-v1.schema.json` defines structured battle evidence
- `tools/ingest_battle_state.py` validates and normalizes battle-state JSON locally
- `tools/browser_damage_calc.py` provides the optional exact damage helper

## Notes

- This package is generated from the canonical repo source. Do not edit the packaged copies by hand.
- Runtime-specific install and update instructions are maintained in the main repository docs for `vgc-coach`.
"""


def render_codex_manifest(plugin: dict, repo_meta: dict, skills: Dict[str, SkillInfo], version: str) -> dict:
    prompts = [
        trim_codex_prompt(skills[name].default_prompt)
        for name in plugin["default_prompt_skills"]
    ]
    return {
        "name": plugin["name"],
        "version": version,
        "description": plugin["description"],
        "author": repo_meta["author"],
        "homepage": repo_meta["homepage"],
        "repository": repo_meta["repository"],
        "license": repo_meta["license"],
        "keywords": plugin["keywords"],
        "skills": "./skills/",
        "interface": {
            "displayName": "VGC Coach",
            "shortDescription": "Pokemon Champions coaching skills for Codex",
            "longDescription": "Installable Pokemon Champions coaching workflows generated from the canonical shared VGC Coach skill packages.",
            "developerName": repo_meta["author"]["name"],
            "category": "Productivity",
            "capabilities": plugin["capabilities"],
            "websiteURL": repo_meta["homepage"],
            "defaultPrompt": prompts,
            "brandColor": plugin["brand_color"],
        },
    }


def render_claude_manifest(plugin: dict, repo_meta: dict, version: str) -> dict:
    return {
        "name": plugin["name"],
        "description": plugin["description"],
        "version": version,
        "author": repo_meta["author"],
        "homepage": repo_meta["homepage"],
        "repository": repo_meta["repository"],
        "license": repo_meta["license"],
        "keywords": plugin["keywords"],
    }


def render_opencode_package_json(plugin: dict, repo_meta: dict, version: str) -> dict:
    return {
        "name": plugin["name"],
        "version": version,
        "type": "module",
        "description": plugin["description"],
        "homepage": repo_meta["homepage"],
        "repository": repo_meta["repository"],
        "license": repo_meta["license"],
        "keywords": plugin["keywords"],
        "main": "./.opencode/plugins/vgc-coach.js",
    }


def render_opencode_plugin_js(plugin_name: str) -> str:
    return f"""import path from 'path';
import {{ fileURLToPath }} from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export const VgcCoachPlugin = async () => {{
  const pluginRoot = path.resolve(__dirname, '..', '..');
  const skillsDir = path.join(pluginRoot, 'skills');

  return {{
    config: async (config) => {{
      config.skills = config.skills || {{}};
      config.skills.paths = config.skills.paths || [];
      if (!config.skills.paths.includes(skillsDir)) {{
        config.skills.paths.push(skillsDir);
      }}
    }},
  }};
}};
"""


def render_root_package_json(plugin: dict, repo_meta: dict, version: str) -> dict:
    return {
        "name": plugin["name"],
        "version": version,
        "type": "module",
        "description": plugin["description"],
        "homepage": repo_meta["homepage"],
        "repository": repo_meta["repository"],
        "license": repo_meta["license"],
        "keywords": plugin["keywords"],
        "main": "./plugins/vgc-coach-opencode/.opencode/plugins/vgc-coach.js",
    }


def render_site_package_json(version: str) -> dict:
    site_package_path = ROOT / "site" / "package.json"
    _prewalk_source_tree(site_package_path)
    package = json.loads(site_package_path.read_text())
    package["version"] = version
    return package


def render_codex_marketplace(version: str) -> dict:
    return {
        "name": "vgc-coach",
        "interface": {
            "displayName": "VGC Coach",
        },
        "plugins": [
            {
                "name": "vgc-coach-codex",
                "source": {
                    "source": "local",
                    "path": "./plugins/vgc-coach-codex",
                },
                "policy": {
                    "installation": "AVAILABLE",
                    "authentication": "ON_INSTALL",
                },
                "category": "Productivity",
            }
        ],
    }


def render_claude_marketplace(repo_meta: dict, version: str) -> dict:
    return {
        "name": "vgc-coach",
        "owner": repo_meta["author"],
        "metadata": {
            "description": "Pokemon Champions coaching plugins generated from the shared VGC Coach skill packages.",
            "version": version,
            "pluginRoot": "./plugins",
        },
        "plugins": [
            {
                "name": "vgc-coach-claude",
                "source": "./plugins/vgc-coach-claude",
                "description": "Pokemon Champions coaching skills for Claude Code.",
                "version": version,
                "author": repo_meta["author"],
            }
        ],
    }


def render_release_notes(manifest: dict, version: str) -> str:
    release_date = manifest["release_notes"]["date"]
    bullets = "\n".join(f"- {item}" for item in manifest["release_notes"]["summary"])
    return f"""# Release Notes

{GENERATED_COMMENT}

## {version} - {release_date}

{bullets}
"""


def build_plugin(plugin: dict, manifest: dict, skills: Dict[str, SkillInfo], version: str, target_root: Path) -> None:
    repo_meta = manifest["repository"]
    plugins_root = target_root / "plugins"
    assert_destination_contained(target_root, plugins_root)
    destination = plugins_root / plugin["name"]
    if destination.exists() or destination.is_symlink():
        safe_rmtree(destination, plugins_root)
    safe_mkdir(destination, plugins_root)

    for relative in manifest["shared_copy"]["files"]:
        copy_path(ROOT / relative, destination / relative, destination)
    for relative in manifest["shared_copy"]["directories"]:
        copy_path(ROOT / relative, destination / relative, destination)
    for relative in manifest["shared_copy"]["tools"]:
        copy_path(ROOT / relative, destination / relative, destination)

    for skill_name in skills:
        copy_path(
            ROOT / "skills" / skill_name,
            destination / "skills" / skill_name,
            destination,
            ignore=ignore_hidden_entries,
        )

    for relative in collect_skill_docs(manifest):
        copy_path(ROOT / relative, destination / relative, destination)

    for relative in plugin["runtime_docs"]:
        if relative.endswith(".md") and "docs/runtime/" in relative:
            write_text(
                destination / relative,
                render_package_runtime_doc(plugin),
                destination,
            )
            continue
        copy_path(ROOT / relative, destination / relative, destination)

    write_text(
        destination / "README.md",
        render_plugin_readme(plugin, manifest, skills, version),
        destination,
    )

    if plugin["runtime"] == "codex":
        write_json(
            destination / plugin["manifest_path"],
            render_codex_manifest(plugin, repo_meta, skills, version),
            destination,
        )
        return

    if plugin["runtime"] == "claude":
        write_json(
            destination / plugin["manifest_path"],
            render_claude_manifest(plugin, repo_meta, version),
            destination,
        )
        return

    if plugin["runtime"] == "opencode":
        write_json(
            destination / plugin["manifest_path"],
            render_opencode_package_json(plugin, repo_meta, version),
            destination,
        )
        write_text(
            destination / ".opencode" / "plugins" / "vgc-coach.js",
            render_opencode_plugin_js(plugin["name"]),
            destination,
        )
        return

    raise ValueError(f"Unsupported runtime: {plugin['runtime']}")


def build_root_outputs(manifest: dict, version: str, target_root: Path) -> None:
    repo_meta = manifest["repository"]
    opencode_plugin = next(
        plugin for plugin in manifest["plugins"] if plugin["runtime"] == "opencode"
    )
    write_json(
        target_root / ".agents" / "plugins" / "marketplace.json",
        render_codex_marketplace(version),
        target_root,
    )
    write_json(
        target_root / ".claude-plugin" / "marketplace.json",
        render_claude_marketplace(repo_meta, version),
        target_root,
    )
    write_json(
        target_root / "package.json",
        render_root_package_json(opencode_plugin, repo_meta, version),
        target_root,
    )
    write_json(
        target_root / "site" / "package.json",
        render_site_package_json(version),
        target_root,
    )


def build_all(target_root: Path) -> None:
    manifest = load_manifest()
    validate_manifest_paths(manifest)
    validate_canonical_sources(manifest)
    version = load_version()
    skills = load_skills(manifest)
    for plugin in manifest["plugins"]:
        build_plugin(plugin, manifest, skills, version, target_root)
    build_root_outputs(manifest, version, target_root)


def compare_directories(expected: Path, actual: Path) -> List[str]:
    differences: List[str] = []
    comparison = filecmp.dircmp(expected, actual)
    for name in comparison.left_only:
        differences.append(f"Missing in repo: {actual / name}")
    for name in comparison.right_only:
        differences.append(f"Unexpected in repo: {actual / name}")
    for name in comparison.common_files:
        if not filecmp.cmp(expected / name, actual / name, shallow=False):
            differences.append(f"Changed file: {actual / name}")
    for subdir in comparison.common_dirs:
        differences.extend(compare_directories(expected / subdir, actual / subdir))
    return differences


def validate_no_symlinks(root: Path) -> List[str]:
    issues: List[str] = []

    def walk(path: Path) -> None:
        mode = path.lstat().st_mode
        if stat.S_ISLNK(mode):
            issues.append(f"Symlink not allowed: {path}")
            return
        if not stat.S_ISDIR(mode):
            return
        with os.scandir(path) as entries:
            for entry in entries:
                walk(Path(entry.path))

    if root.exists() or root.is_symlink():
        walk(root)
    return issues


def validate_no_workspace_references(root: Path) -> List[str]:
    issues: List[str] = []
    forbidden = [
        ".agents/skills/",
        ".claude/skills/",
        ".opencode/skills/",
        str(ROOT),
    ]
    def regular_files(path: Path) -> Iterable[Path]:
        mode = path.lstat().st_mode
        if stat.S_ISLNK(mode):
            return
        if stat.S_ISDIR(mode):
            with os.scandir(path) as entries:
                for entry in entries:
                    yield from regular_files(Path(entry.path))
            return
        if stat.S_ISREG(mode):
            yield path

    if not root.exists() or root.is_symlink():
        return issues
    for path in regular_files(root):
        if path.is_symlink():
            continue
        try:
            content = path.read_text()
        except UnicodeDecodeError:
            continue
        for needle in forbidden:
            if needle in content:
                issues.append(f"Workspace-only reference in {path}: {needle}")
    return issues


def validate_generated_outputs(target_root: Path) -> List[str]:
    issues: List[str] = []
    plugins_dir = target_root / "plugins"
    if plugins_dir.exists() or plugins_dir.is_symlink():
        issues.extend(validate_no_symlinks(plugins_dir))
        issues.extend(validate_no_workspace_references(plugins_dir))
    return issues


def check_repo() -> int:
    with tempfile.TemporaryDirectory() as tmp:
        temp_root = Path(tmp)
        build_all(temp_root)
        differences: List[str] = []
        generated_issues = validate_generated_outputs(ROOT)
        differences.extend(generated_issues)
        if not any(issue.startswith("Symlink not allowed:") for issue in generated_issues):
            differences.extend(compare_directories(temp_root / "plugins", ROOT / "plugins"))
        for relative in [
            ".agents/plugins/marketplace.json",
            ".claude-plugin/marketplace.json",
            "package.json",
            "site/package.json",
        ]:
            if not (ROOT / relative).exists():
                differences.append(f"Missing generated file: {ROOT / relative}")
                continue
            if (temp_root / relative).read_text() != (ROOT / relative).read_text():
                differences.append(f"Changed file: {ROOT / relative}")
        expected_release_notes = render_release_notes(load_manifest(), load_version())
        if not RELEASE_NOTES_PATH.exists():
            differences.append(f"Missing generated file: {RELEASE_NOTES_PATH}")
        elif RELEASE_NOTES_PATH.read_text() != expected_release_notes:
            differences.append(f"Changed file: {RELEASE_NOTES_PATH}")
        if differences:
            for issue in differences:
                print(issue, file=sys.stderr)
            return 1
    return 0


def update_release_notes() -> None:
    manifest = load_manifest()
    version = load_version()
    write_text(RELEASE_NOTES_PATH, render_release_notes(manifest, version), ROOT)


def print_release_notes() -> None:
    manifest = load_manifest()
    version = load_version()
    print(render_release_notes(manifest, version))


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser()
    subparsers = parser.add_subparsers(dest="command", required=True)
    subparsers.add_parser("build")
    subparsers.add_parser("check")
    subparsers.add_parser("update-release-notes")
    subparsers.add_parser("print-release-notes")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    if args.command == "build":
        build_all(ROOT)
        return 0
    if args.command == "check":
        return check_repo()
    if args.command == "update-release-notes":
        update_release_notes()
        return 0
    if args.command == "print-release-notes":
        print_release_notes()
        return 0
    raise ValueError(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    raise SystemExit(main())
