#!/usr/bin/env python3
"""Validate the shared live-source registry and render its markdown companion."""

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_REGISTRY_PATH = (
    REPO_ROOT / "docs" / "skills" / "shared" / "references" / "live-source-registry.yaml"
)
DEFAULT_OUTPUT_PATH = (
    REPO_ROOT / "docs" / "skills" / "shared" / "references" / "live-source-map.md"
)
GENERATED_COMMENT = (
    "<!-- Generated by tools/render_source_registry_docs.py from "
    "docs/skills/shared/references/live-source-registry.yaml -->"
)

VALID_ROLES = {
    "official_regulation",
    "official_transition",
    "tournament_meta",
    "broader_meta",
    "supporting_sets",
    "editorial_context",
}
VALID_CLAIM_TYPES = {
    "legality",
    "mechanics",
    "format_dates",
    "held_item_rules",
    "timers",
    "event_timing",
    "transition_context",
    "tournament_usage",
    "top_teams",
    "current_snapshot",
    "ladder_usage",
    "win_rate",
    "winning_teams",
    "core_pairs",
    "set_tendencies",
    "common_partners",
    "move_tendencies",
    "item_tendencies",
    "ability_tendencies",
    "event_context",
    "tournament_coverage",
    "editorial_interpretation",
}
MINIMUM_STACK_KEYS = ("official", "tournament_meta", "broader_meta")
ROLE_GROUPS = (
    ("Official Format Sources", ("official_regulation", "official_transition")),
    ("Community Meta Sources", ("tournament_meta", "broader_meta")),
    ("Supporting Sources", ("supporting_sets", "editorial_context")),
)


def _require_mapping(value: Any, *, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be a mapping")
    return value


def _require_list(value: Any, *, label: str) -> list[Any]:
    if not isinstance(value, list):
        raise ValueError(f"{label} must be a list")
    return value


def _require_nonempty_string(value: Any, *, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{label} must be a non-empty string")
    return value.strip()


def _require_bool(value: Any, *, label: str) -> bool:
    if not isinstance(value, bool):
        raise ValueError(f"{label} must be a boolean")
    return value


def _require_int(value: Any, *, label: str) -> int:
    if not isinstance(value, int):
        raise ValueError(f"{label} must be an integer")
    return value


def _validate_string_list(values: Any, *, label: str) -> list[str]:
    raw_items = _require_list(values, label=label)
    normalized = [_require_nonempty_string(item, label=f"{label} item") for item in raw_items]
    if not normalized:
        raise ValueError(f"{label} must not be empty")
    return normalized


def validate_registry(payload: Any) -> dict[str, Any]:
    root = _require_mapping(payload, label="registry")
    version = _require_nonempty_string(root.get("version"), label="version")
    summary = _require_nonempty_string(root.get("summary"), label="summary")
    usage = _require_nonempty_string(root.get("usage"), label="usage")

    minimum_stack_raw = _require_mapping(root.get("minimum_stack"), label="minimum_stack")
    minimum_stack: dict[str, int] = {}
    for key in MINIMUM_STACK_KEYS:
        minimum_stack[key] = _require_int(minimum_stack_raw.get(key), label=f"minimum_stack.{key}")
        if minimum_stack[key] < 0:
            raise ValueError(f"minimum_stack.{key} must be >= 0")

    sources: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    seen_priorities: set[int] = set()
    for index, source in enumerate(_require_list(root.get("sources"), label="sources"), start=1):
        item = _require_mapping(source, label=f"sources[{index}]")
        source_id = _require_nonempty_string(item.get("id"), label=f"sources[{index}].id")
        if source_id in seen_ids:
            raise ValueError(f"duplicate source id: {source_id}")
        seen_ids.add(source_id)

        role = _require_nonempty_string(item.get("role"), label=f"sources[{index}].role")
        if role not in VALID_ROLES:
            raise ValueError(f"invalid role for {source_id}: {role}")

        priority = _require_int(item.get("priority"), label=f"sources[{index}].priority")
        if priority in seen_priorities:
            raise ValueError(f"duplicate priority: {priority}")
        seen_priorities.add(priority)

        allowed_claim_types = _validate_string_list(
            item.get("allowed_claim_types"),
            label=f"sources[{index}].allowed_claim_types",
        )
        invalid_claim_types = sorted(set(allowed_claim_types) - VALID_CLAIM_TYPES)
        if invalid_claim_types:
            raise ValueError(
                f"invalid claim types for {source_id}: {', '.join(invalid_claim_types)}"
            )

        normalized = {
            "id": source_id,
            "display_name": _require_nonempty_string(
                item.get("display_name"),
                label=f"sources[{index}].display_name",
            ),
            "role": role,
            "priority": priority,
            "allowed_claim_types": allowed_claim_types,
            "required_for_minimum_stack": _require_bool(
                item.get("required_for_minimum_stack"),
                label=f"sources[{index}].required_for_minimum_stack",
            ),
            "use_for": _validate_string_list(item.get("use_for"), label=f"sources[{index}].use_for"),
            "do_not_use_for": _validate_string_list(
                item.get("do_not_use_for"),
                label=f"sources[{index}].do_not_use_for",
            ),
            "fallback_if_unavailable": _validate_string_list(
                item.get("fallback_if_unavailable"),
                label=f"sources[{index}].fallback_if_unavailable",
            ),
        }
        sources.append(normalized)

    if sorted(source["priority"] for source in sources) != list(range(1, len(sources) + 1)):
        raise ValueError("source priorities must be contiguous and start at 1")

    return {
        "version": version,
        "summary": summary,
        "usage": usage,
        "minimum_stack": minimum_stack,
        "sources": sorted(sources, key=lambda item: item["priority"]),
    }


def load_registry(path: Path = DEFAULT_REGISTRY_PATH) -> dict[str, Any]:
    raw = yaml.safe_load(path.read_text())
    return validate_registry(raw)


def _render_source(source: dict[str, Any]) -> list[str]:
    lines = [f"### {source['display_name']}", ""]
    lines.append(f"Role: `{source['role']}`")
    lines.append("")
    lines.append("Use for:")
    lines.append("")
    for item in source["use_for"]:
        lines.append(f"- {item}")
    lines.append("")
    lines.append("Do not use for:")
    lines.append("")
    for item in source["do_not_use_for"]:
        lines.append(f"- {item}")
    lines.append("")
    if source["required_for_minimum_stack"]:
        lines.append("Counts toward the recommended minimum live stack.")
        lines.append("")
    lines.append("Fallback if unavailable:")
    lines.append("")
    for item in source["fallback_if_unavailable"]:
        lines.append(f"- {item}")
    lines.append("")
    return lines


def render_markdown(registry: dict[str, Any]) -> str:
    lines = [
        "# Shared Live Source Map",
        "",
        GENERATED_COMMENT,
        "",
        registry["summary"],
        "",
        registry["usage"],
        "",
    ]

    for heading, roles in ROLE_GROUPS:
        lines.append(f"## {heading}")
        lines.append("")
        for source in registry["sources"]:
            if source["role"] in roles:
                lines.extend(_render_source(source))

    lines.extend(
        [
            "## Recommended Minimum Live Stack",
            "",
            "For most current-meta questions and current-field team recommendations, use at least:",
            "",
            f"1. {registry['minimum_stack']['official']} official regulation source",
            f"2. {registry['minimum_stack']['tournament_meta']} tournament-focused community source",
            f"3. {registry['minimum_stack']['broader_meta']} broader usage/community source",
            "",
            "If those disagree materially, say so and keep the conclusion directional.",
            "",
        ]
    )
    return "\n".join(lines)


def build_docs(
    *,
    registry_path: Path = DEFAULT_REGISTRY_PATH,
    output_path: Path = DEFAULT_OUTPUT_PATH,
) -> str:
    rendered = render_markdown(load_registry(registry_path))
    output_path.write_text(rendered)
    return rendered


def check_docs(
    *,
    registry_path: Path = DEFAULT_REGISTRY_PATH,
    output_path: Path = DEFAULT_OUTPUT_PATH,
) -> bool:
    rendered = render_markdown(load_registry(registry_path))
    committed = output_path.read_text()
    return rendered == committed


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Validate the shared live-source registry and render its markdown companion."
    )
    parser.add_argument("command", choices=("build", "check"), nargs="?", default="build")
    parser.add_argument("--registry", type=Path, default=DEFAULT_REGISTRY_PATH)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT_PATH)
    args = parser.parse_args()

    if args.command == "build":
        build_docs(registry_path=args.registry, output_path=args.output)
        return 0

    if check_docs(registry_path=args.registry, output_path=args.output):
        return 0

    print(
        f"{args.output} is out of date with {args.registry}. "
        "Run `python3 tools/render_source_registry_docs.py build`.",
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
